# Generated by Django 2.2.6 on 2021-09-20 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='problem',
            name='tag',
        ),
        migrations.AddField(
            model_name='problem',
            name='u_id',
            field=models.IntegerField(default=1, verbose_name='ユーザid'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='problem',
            name='site_url',
            field=models.URLField(max_length=150, verbose_name='URL'),
        ),
        migrations.AddField(
            model_name='problem',
            name='tags',
            field=models.ManyToManyField(blank=True, to='app.Tag'),
        ),
    ]
