# Generated by Django 2.2.6 on 2021-09-19 14:42

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20210919_1652'),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_dic', app.models.StandardJSONField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=50, verbose_name='ユーザー名')),
                ('password', models.CharField(max_length=50, verbose_name='パスワード')),
            ],
        ),
    ]
